myokit/myokit

- .flake8
- .travis.yml
- myokit/__init__.py
- myokit/_aux.py
- myokit/_exec_new.py
- myokit/_exec_old.py
- myokit/_expressions.py
- myokit/_model_api.py
- myokit/_old_exec.py
- myokit/formats/axon/_abf.py
- myokit/formats/wcp/_wcp.py
- myokit/lib/markov.py
- myokit/pype.py
- tests/test_datablock.py
See #230 
This Python version was released in November 2013, which is hopefully far enough back in time to work on most servers, macbooks, etc.
2.7.6 is also the oldest version testable on Travis.
> Test Myokit on Python 2.7.6 (shipped with Ubuntu LTS 14.04)

- myokit/_datalog.py
- myokit/tests/test_datalog.py
- myokit/tests/test_simulation_log_interval.py
Was a bit confused it didn't find a time before. Makes sense in original context of use, but requires more clarity to user
> Rename DataLog.find() to find_after().

- myokit/_sim/sundials.py
Stops it from breaking when converting `'3-dev'` to int
> Fix for sundials versions like 1.2.3-dev

- myokit/_model_api.py
- myokit/formats/cellml/_importer.py
- myokit/tests/test_component.py
- myokit/tests/test_model.py
Cellml states were in order of appearance of the equations, now are in order of appearance of the variables.
> Cellml state variable ordering

- .travis.yml
https://stackoverflow.com/questions/38670295/homebrew-refusing-to-link-openssl
Seems sundials does install openssl
> ==> Installing sundials dependency: openssl@1.1
> Trying to fix travis osx build

- myokit/_model_api.py
- myokit/formats/cellml/v1/_parser.py
- myokit/gui/__init__.py
- myokit/tests/test_cellml_v1_parser.py
- myokit/tests/test_variable.py
Three fixes:
- Fixed bug in Model.convert_units; now also converting references to derivatives
- Stopped allowing empty <units> elements in CellML 1.0 and 1.1
- Updated GUI code to not crash if gui back-end was already set
> Three fixes

- myokit/formats/cellml/v1/_api.py
- myokit/tests/test_cellml_v1_api.py
- myokit/tests/test_cellml_v1_parser.py
It's a bit unclear from the spec if it's supposed to, but it seems the more sensible choice
> CellML v1 API now complains about duplicate imports

- myokit/lib/plots.py
- myokit/tests/test_lib_plots.py
now has an option to bundle all remaining currents into one, which is useful when plotting the relative contribution of each current to the net current.
> Cumulative current plot

- myokit/_sim/cable.py
- myokit/_sim/compiler.py
- myokit/_sim/fiber_tissue.py
- myokit/_sim/icsim.py
- myokit/_sim/jacobian.py
- myokit/_sim/opencl.py
- myokit/_sim/openclsim.py
- myokit/_sim/psim.py
- myokit/_sim/rhs.py
- myokit/_sim/sundials.py
> All compiled modules now use a pid-based hash in there name. 

- myokit/formats/cellml/v1/_writer.py
> CellML v1 writer now ensures no spaces around numbers in initial values or unit multipliers

- .travis.yml
- docs/source/api_formats/cellml_v1.rst
- docs/source/api_formats/cellml_v2.rst
- docs/source/api_index/myokit.formats.rst
- myokit/__init__.py
- myokit/_aux.py
- myokit/_expressions.py
- myokit/_model_api.py
- myokit/formats/cellml/v1/__init__.py
- myokit/formats/cellml/v1/_api.py
- myokit/formats/cellml/v2/__init__.py
- myokit/formats/cellml/v2/_api.py
- myokit/formats/cellml/v2/_parser.py
- myokit/tests/test_aux.py
- myokit/tests/test_cellml_v1_api.py
- myokit/tests/test_cellml_v1_parser.py
- myokit/tests/test_cellml_v2_api.py
- myokit/tests/test_cellml_v2_parser.py
- myokit/tests/test_expressions.py
- myokit/tests/test_model.py
- myokit/tests/test_unit.py
A more lenient equality comparison was required, see #575 
While implementing this, it made sense to also start allowing floating point exponents (e.g. `mV^1.23`).
The only reason this was not implemented was to avoid the hassle of lenient equality checks.
Allowing non-integer exponents removed a restriction for CellML 1 and 2, so updated that as well...
> Unit system: Lax equality comparison and floating point exponents

- myokit/formats/sbml/_api.py
- myokit/formats/sbml/_parser.py
- myokit/tests/test_sbml_api.py
- myokit/tests/test_sbml_parser.py
- moved myokit_model tests to bottom of sbml api test file
- rewrote a few tests to avoid parser
- updated compartment size test to add missing tests for rate
- in general, these tests shouldn't test private methods, just the public API!
- seems that setting rates for sizes wasn't covered in the tests? new test fails
> Sbml tweaks

- CHANGELOG.md
- myokit/_model_api.py
- myokit/gui/ide.py
- myokit/gui/source.py
- myokit/tests/test_model.py
#589 
- adds has_parse_info()
- adds show_line_of(var, **raw**)
- adds Ctrl+J to jump to var def in ide
> Add jump-to-variable function in IDE

- .travis-opencl.sh
- .travis.yml
- CHANGELOG.md
- Removed Python 2.7.6 tests (which no longer ran)
- Added OpenCL headers and intel runtime for ubuntu tests
- Stopped OS/X from reinstalling 100s of packages with homebrew
- Made OS/X tests use python 3
> Travis updates: OpenCL on Ubuntu, faster OS/X install, Removed Python 2.7.6

- CHANGELOG.md
- myokit/_config.py
- myokit/tests/test_config.py
and closing semicolons. Closes #688.
> Path lists read from myokit.ini are now filtered for empty entries 

- CHANGELOG.md
- myokit/_model_api.py
- myokit/_protocol.py
- myokit/tests/test_model.py
- myokit/tests/test_protocol.py
> Removed 3 deprecated methods.

- CHANGELOG.md
- myokit/_sim/fiber_tissue.py
- myokit/_sim/mcl.h
- myokit/_sim/opencl.c
- myokit/_sim/opencl.py
- myokit/_sim/openclsim.c
- myokit/_sim/openclsim.cl
- myokit/_sim/openclsim.py
- myokit/tests/data/br-1977.mmt
- myokit/tests/shared.py
- myokit/tests/test_simulation_opencl.py
- test.py
See #743 
The atomic add operation for floating points only works on floats. Replaced with a version that (1) fixes this, and (2) avoids another possible problem (see https://streamhpc.com/blog/2016-02-09/atomic-operations-for-floats-in-opencl-improved)
> OpenCL sim connections with double precision

- CHANGELOG.md
- myokit/formats/mathml/_parser.py
- myokit/tests/test_formats_mathml_content.py
Currently raises attribute error, should be informative parse error
> Deal with empty <cn> in mathml

- myokit/_config.py
> Config file reader now expands ~ and env vars in path lists.

- CHANGELOG.md
- docs/source/conf.py
- examples/t4-opencl-simulation.ipynb
- myokit/_sim/openclsim.py
- myokit/tests/test_simulation_opencl.py
Replaced `OpenCLSimulation.calculate_conductance` with a method `monodomain_conductance` (which takes slightly different parameters).
Fixes #772
> Fix bug in calculate_conductance

- myokit/_sim/cmodel.h
- myokit/_sim/cmodel.py
- myokit/tests/test_simulation_cvodes.py
See #759 
This was a really sneaky one: the method that let CVODES change the parameters for its finite difference scheme was using the wrong ordering, so CVODES got the ordering of the parameters wrong.
> Sensitivity ordering bug

- .flake8
- CHANGELOG.md
- myokit/_expressions.py
- myokit/_model_api.py
- myokit/_parsing.py
- myokit/_protocol.py
- myokit/_unit.py
- myokit/tests/test_component.py
- myokit/tests/test_expressions.py
- myokit/tests/test_model.py
- myokit/tests/test_quantity.py
- myokit/tests/test_unit.py
- myokit/tests/test_variable.py
See #842 
- Pickling an expression now raises an error which suggests an alternative way to serialise expressions.
- myokit.parse_expression() now accepts a model as a context.
- model comparison with `==` is now back to the default `is` implementation. The old `==` overload is available as `Model.is_similar`
- Model.get() and Component.get() raise errors if objects from a different model are passed in
- Hashes for equation and quantity were fixed, equations are now immutable.
> Pickling, hash & equality details

- CHANGELOG.md
- myokit/lib/plots.py
Slightly tweaked the plotting in `myokit.lib.plots.cumulative_current`, and added two arguments `line_args` and `fill_args` that can be used to customize the plotting style.
> Added line_args and fill_args arguments to cumulative_current().

- CHANGELOG.md
- myokit/_sim/cvodessim.c
- myokit/tests/memory/memleak.py
Only in cvodessim, not in cvode sim.
Introduced when switching from list to sequence interface for `log_times` handling
> Memory leak when using `log_times`

- myokit/_expressions.py
- myokit/_model_api.py
- myokit/tests/test_model.py
Simplified `Model.evaluate_derivatives`, making it use `subst()` instead of changing any variable RHS equations. 
Closes #906.
> Simplified Model.evaluate_derivatives

- myokit/_sim/cvodessim.py
> Catching any exception type from evaluate_derivatives in cvodes sim numerical error handling.

- CHANGELOG.md
- myokit/__init__.py
- myokit/__main__.py
- myokit/formats/axon/_abf.py
Part of #964 
`logging.basicConfig` should be called
- from within __name__ == '__main__'
- by scripts and applications
So not by myokit when used as a library, only when via __main__
> Only call basicConfig from within a 'if __name__ == main'

- CHANGELOG.md
- myokit/formats/sbml/_api.py
- myokit/tests/test_sbml_api.py
- myokit/tests/test_sbml_parser.py
> Renamed 'myokit' component in imported SBML documents to 'global'.

- CHANGELOG.md
- myokit/_io.py
- myokit/tests/test_io.py
> `myokit.save()` now raises a `ValueError` if `model`, `protocol`, and `script` are all None.

- CHANGELOG.md
- docs/source/api_gui/ide.rst
- docs/source/cmd/system.rst
- myokit/__init__.py
- myokit/__main__.py
- myokit/_config.py
- myokit/_system.py
- myokit/gui/__init__.py
- myokit/gui/datablock_viewer.py
- myokit/gui/datalog_viewer.py
- myokit/gui/explorer.py
- myokit/gui/ide.py
- myokit/gui/progress.py
- myokit/gui/source.py
- myokit/tests/test_config.py
- setup.py
> Add PyQt6 and PySide6 support

- CHANGELOG.md
- docs/source/api_formats/index.rst
- docs/source/api_index/myokit.formats.rst
- myokit/_model_api.py
- myokit/_sim/openclsim.py
- myokit/formats/__init__.py
- myokit/formats/axon/_abf.py
- myokit/formats/axon/_atf.py
- myokit/formats/axon/_importer.py
- myokit/formats/wcp/_wcp.py
- myokit/gui/datalog_viewer.py
- myokit/tests/test_datalog.py
- myokit/tests/test_formats_axon.py
- myokit/tests/test_formats_wcp.py
See #984 
- `channel(integer_or_name, join_sweeps)` --> (time, data)
- `channel_count`
- `channel_names`
- `log(join_sweeps, use_names, channels)` to get a DataLog
- `sweep_count`
- `len`, `iter`, and `[integer]` to access sweeps
- `filename`, `path`
- `matplotlib_figure` --> a figure (does not show)
- `version` --> string
> Better DataLog conversion in ABF, ATF, WCP

- .readthedocs.txt
- .readthedocs.yaml
- CONTRIBUTING.md
- Will be required starting September 23
- Offers finer grained control than web interface
https://blog.readthedocs.com/migrate-configuration-v2/
> Adding readthedocs.yaml configuration file

- .github/workflows/unit-tests-windows-miniconda.yml
- CHANGELOG.md
- docs/source/api_core/Model.rst
- docs/source/api_index/myokit.rst
- docs/source/api_simulations/DataLog.rst
- myokit/__init__.py
- myokit/_datalog.py
- myokit/_model_api.py
- myokit/formats/axon/_abf.py
- myokit/formats/heka/_patchmaster.py
- myokit/formats/wcp/_wcp.py
- myokit/tests/data/lr-1991.mmt
- myokit/tests/test_datalog.py
- DataLog now stores meta data in `.meta` and per-column meta data in `.cmeta`. Both can only be key-value pairs of strings. Closes #958
- A DataLog can now export its meta data in [CSV-on-the-web](https://w3c.github.io/csvw/) format. Closes #162
> Meta data support in DataLog

- CHANGELOG.md
- myokit/_datalog.py
- myokit/formats/heka/_patchmaster.py
- myokit/tests/test_datalog.py
- Made DataLog read meta data when using save/load, which are supposed to be "proper" saving/loading of all parts of a log
- Did not do same for save_csv and load_csv, which are export/import type options
- PatchMasterFile no longer performs "zero offset subtraction" on recorded currents by default. This is nothing to do with "zeroing the current" before making the seal, but is an analysis option to make the current in a chosen stimulus segment be zero.
> Heka offset and datalog meta read

- myokit/_sim/__init__.py
- myokit/_sim/cmodel.h
- myokit/_sim/cvodessim.c
After Chon reported this on a server:
```
Traceback (most recent call last):
File "/home/chonloklei/testing-myokit/run.py", line 9, in <module>
sim = myokit.Simulation(model)
File "/home/chonloklei/voltage-clamp-decipher/env/lib/python3.9/site-packages/myokit/_sim/cvodessim.py", line 204, in __init__
self._create_simulation(cmodel.code, path)
File "/home/chonloklei/voltage-clamp-decipher/env/lib/python3.9/site-packages/myokit/_sim/cvodessim.py", line 272, in _create_simulation
res = self._compile(
File "/home/chonloklei/voltage-clamp-decipher/env/lib/python3.9/site-packages/myokit/_sim/__init__.py", line 231, in _compile
raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command '/usr/bin/gcc' failed with exit code 1 …
```
> Made some changes to new C code to make it more C89-ish

- CHANGELOG.md
- docs/source/api_formats/heka.rst
- docs/source/api_index/myokit.formats.rst
- myokit/formats/heka/__init__.py
- myokit/formats/heka/_patchmaster.py
- myokit/gui/datalog_viewer.py
@chonlei
This adds some code to deal with the `.amp` segment of a file, and updates the viewer to show incomplete traces (it wasn't showing any for Alex's data, presumably because it couldn't parse the stimulus and so couldn't determine that the traces were from completed recordings).
The code isn't finished.
In particularly, it sticks a load of information in a property called `._temp`.
If you can figure out what these fields (or any others you want to add) mean, what units they're in etc., then we can add proper methods for them (with docstrings that say what they mean).
This script reads a file and prints all the *unparsed* amplifier info (so not the stuff where I actually know exactly what it means):
```
#!/usr/bin/env python3
import myokit
import myokit.formats.heka as heka
files = [ …
```
> Patchmaster updates to read more amplifier properties

- CHANGELOG.md
- myokit/lib/markov.py
set_constant can change parameter values which means the previously cached matrices and solutions are no longer valid (same reasoning as set_parameters which already invalidates the cache).
The cache is now invalidated in set_constant to match set_parameters
Closes #1044
> Fixed bug in MarkovModel cache

- CHANGELOG.md
- myokit/_model_api.py
- myokit/_sim/cvodessim.c
- myokit/_sim/cvodessim.py
- myokit/tests/test_model.py
- myokit/tests/test_simulation_cvodes.py
Simulation
- Renamed `last_state` to `crash_state` to differentiate from `last_number_of_steps` etc.
- Added a `crash_inputs` to get the bindings, and updated the simulation error handling to use the exact bindings when trying to reproduce the error in Python
- Renamed `Simulation.eval_derivatives` to `evaluate_derivatives` and made it use the default_state instead of state (if no state is specified), to be more consistent (binding values were already not used, regardless of their current values). Upgrade the binding handling so that time etc can be set.
Model
- Made `model.evaluate_derivatives` use an `np.errstate(all='raise')` (when not explicitly ignoring errors) to catch more numerical issues
> Improvements to evaluate_derivatives() methods and cvodes error display.

- CHANGELOG.md
- myokit/lib/hh.py
- myokit/tests/test_lib_hh.py
Fixed issue #1059 by forcing initial condition when _t=0 in the HH analytical simulation
Added a test to ensure this fix doesn't break with the changes in #943 and #571 
The test verifies that:
- An overflow warning is triggered
- No nans are present in the current or the overflown state variable
- The state is correctly solved for tau=0 (starts at initial state then jumps to steady state)
> 1059 overflow

- myokit/_err.py
- myokit/_expressions.py
- myokit/_model_api.py
- myokit/tests/test_expressions.py
> Moved testing of Expression operand types from validation into the constructor.

- CHANGELOG.md
- docs/source/api_core/exceptions.rst
- docs/source/api_core/expressions.rst
- docs/source/api_index/myokit.rst
- docs/source/syntax/model.rst
- myokit/__init__.py
- myokit/_err.py
- myokit/_expressions.py
- myokit/_model_api.py
- myokit/_myokit_version.py
- myokit/formats/__init__.py
- myokit/formats/ansic/_ewriter.py
- myokit/formats/opencl/_ewriter.py
- myokit/formats/sympy/_ereader.py
- myokit/tests/test_expressions.py
- myokit/tests/test_formats_ansic.py
- myokit/tests/test_formats_cpp.py
- myokit/tests/test_formats_cuda.py
- myokit/tests/test_formats_easyml.py
- myokit/tests/test_formats_latex.py
- myokit/tests/test_formats_matlab.py
- myokit/tests/test_formats_opencl.py
- myokit/tests/test_formats_python.py
- myokit/tests/test_formats_stan.py
- myokit/tests/test_formats_sympy.py
- myokit/tests/test_parsing.py
> Check that conditions and numerical operators aren't mixed

- CHANGELOG.md
- myokit/_datalog.py
- myokit/tests/test_datalog.py
https://en.wikipedia.org/wiki/Byte_order_mark
> DataLog: Ignore byte order marker (ufeff) at start of csv file

- CHANGELOG.md
- myokit/_unit.py
- myokit/tests/test_quantity.py
- myokit/tests/test_unit.py
Fixes #1115
Removes auto-register in `Unit.__str__`
> bug: remove auto-register for Unit

- myokit/formats/sbml/_api.py
- myokit/tests/test_sbml_export.py
If a myokit model contains a non-constant variable that is not a state variable, the rule is added as an initialAssignment, should be an assigment rule.
> bug(sbml export): fix case of non-constant non-state variable

- .github/workflows/coverage-test.yml
- .github/workflows/docs-test.yml
- .github/workflows/style-test.yml
- .github/workflows/unit-tests-macos.yml
- .github/workflows/unit-tests-numpy.yml
- .github/workflows/unit-tests-sundials.yml
- .github/workflows/unit-tests-ubuntu.yml
- .github/workflows/unit-tests-windows-miniconda.yml
- .github/workflows/unit-tests-windows.yml
- pyproject.toml
- setup.py
Closes #1112 
**Changes**
* Adds a minimal `pyproject.toml` with build-time dependencies.
* Removes manual build-time installs of `wheel` and `setuptools` from github workflows
> Add pyproject.toml

- CHANGELOG.md
- myokit/_sim/cable.c
- myokit/_sim/fiber_tissue.c
Both used wrong signature for a python callable C method
> Fixed compilation error in FiberTissueSimulation and Simulation1d
