myokit/myokit

myokit/_sim/cvode.py
myokit/_sim/pacing.h

Hi Michael,
just introduced the changes from #68.
Take a look if that's what you'd like.

Improve Windows compatibility, #68

---

tests/ansic_event_based_pacing.py
tests/ansic_fixed_form_pacing.py
tests/shared.py
tests/test_datablock.py
tests/test_datalog.py
tests/test_dependency_checking.py
tests/test_expressions.py
tests/test_formats_exporters.py
tests/test_formats_importers.py
tests/test_lib_approx.py
tests/test_lib_common.py
tests/test_lib_fit.py
tests/test_lib_markov.py
tests/test_loadsave.py
tests/test_meta.py
tests/test_model_api.py
tests/test_pacing.py
tests/test_parser.py
tests/test_simulation.py
tests/test_simulation_log_interval.py
tests/test_simulation_opencl.py
tests/test_simulation_opencl_log_interval.py
tests/test_units.py

Add future imports to tests.

---

myokit/_expressions.py
myokit/formats/ansic/_ewriter.py
myokit/formats/cellml/_ewriter.py
myokit/formats/cuda/_ewriter.py
myokit/formats/latex/_ewriter.py
myokit/formats/mathml/_ewriter.py
myokit/formats/matlab/_ewriter.py
myokit/formats/opencl/_ewriter.py
myokit/formats/python/_ewriter.py
myokit/formats/stan/_ewriter.py
myokit/formats/sympy/_ewriter.py
tests/test_ewriters.py
tests/test_expression_writers.py

Add ExpressionWriter tests

---

.travis.yml
myokit/_model_api.py
tests/test_model_api.py

Python 3.4 and 3.5

---

.appveyor.yml
myokit/_sim/__init__.py
tests/test_cvode_simulation.py

Fixes for windows Python 3.4 (Visual C++ 2010)

---

.appveyor.yml
myokit/_sim/jacobian.cpp

Fixes for windows Python 3.5 (Visual C++ 2015)

---

.appveyor.yml

Fixes for windows Python 3.6 (Visual C++ 2015)

---

.flake8
.travis.yml
myokit/_aux.py
myokit/_datablock.py
myokit/_datalog.py
myokit/_model_api.py
myokit/_myokit_version.py
myokit/formats/opencl/template/minilog.py

OS/X came with 2.7.10 as a default, so if it's possible it seems worthwhile to test this.
See #225

Fix #225 array.array problem and add Python 2.7.10 testing

---

myokit/_sim/pacing.h
tests/ansic_event_based_pacing.c
tests/test_protocol_and_pacing.py

Time in pacing system _could_ go beyond max_time (if new_time > max)time), so if used badly could potentially have caused issues.

Minor bug in ansic pacing handling of max_time

---

myokit/lib/markov.py
tests/test_lib_markov.py
tests/test_protocol_and_pacing.py

Issue 233: markov analytical simulation and protocol steps at t=0

---

myokit/lib/hh.py
tests/test_lib_hh.py

Make internal function of HHModel use intermediary variables.

---

.coveragerc
docs/source/api_index/myokit.rst
docs/source/api_simulations/LongSimulations.rst
myokit/__init__.py
myokit/_progress.py
tests/test_progress_reporters.py

Add Timeout ProgressReporter.

---

myokit/lib/markov.py
tests/test_lib_markov.py

Calculate currents in discrete markov simulations

---

myokit/formats/axon/_abf.py
tests/test_formats_axon.py

Added AbfFile.extract_channel method that joins sweeps.

---

myokit/lib/hh.py
tests/test_lib_hh.py

Add log_times argument to HH analytical simulation

---

myokit/gui/ide.py

Added cut/copy/paste options to menu in IDE.

---

myokit/gui/datablock_viewer.py
myokit/gui/datalog_viewer.py
myokit/gui/gde.py
myokit/gui/ide.py

Made GUI applications load when config file is corrupt. Closes #135.

---

myokit/_datalog.py

Improved error messages in DataLog

---

docs/source/api_core/misc.rst
docs/source/api_index/myokit.rst
docs/source/api_simulations/DataLog.rst
myokit/__init__.py
myokit/_aux.py
myokit/_datalog.py
myokit/_model_api.py
myokit/_sim/fiber_tissue.py
myokit/_sim/openclsim.py
myokit/lib/hh.py
myokit/lib/markov.py
tests/test_aux.py
tests/test_formats_exporters.py

Hid methods dimco, lvsd, and natural_sort_key.

---

.travis.yml
myokit/_sim/cvodesim.c
myokit/formats/ansic/template/sim.c

Add support for sundials 4

---

.travis.yml
myokit/_sim/cvodesim.c
myokit/formats/ansic/template/sim.c
myokit/formats/sympy/_ereader.py
myokit/formats/sympy/_ewriter.py
myokit/lib/markov.py
setup.py
tests/shared.py
tests/test_formats_expression_writers.py
tests/test_formats_sympy.py
tests/test_lib_fit.py
tests/test_lib_markov.py

It's common enough, and very useful in e.g. Markov simulations. Will want to use it in the future for more tricks e.g. symbolic derivatives

Added sympy as a dependency

---

myokit/_config.py
myokit/_sim/fiber_tissue.c
myokit/_sim/fiber_tissue.py
myokit/_sim/mcl.h
myokit/_sim/opencl.py
myokit/_sim/openclsim.c
myokit/_sim/openclsim.py

Should now work out of the box. And passes all tests on travis OS/X

Improved OpenCL support on OS/X

---

myokit/gui/ide.py

Added format protocol option to ide. Closes #279

---

myokit/_sim/cable.c
myokit/_sim/cvodesim.c
myokit/_sim/fiber_tissue.c
myokit/_sim/icsim.cpp
myokit/_sim/openclsim.c
myokit/_sim/psim.cpp

Check signals in (long-running) C code

---

.appveyor.yml
.travis.yml
test

Rewrite test script's use of argparser

---

myokit/__main__.py
myokit/_model_api.py
myokit/_protocol.py
myokit/lib/common.py
myokit/lib/fit.py
myokit/lib/markov.py
tests/ansic_event_based_pacing.py
tests/test_protocol_and_pacing.py

Add method Protocol.value_at_times

---

myokit/_sim/cvodesim.c
tests/test_simulation_cvode.py

Model with zero states causes exception for CVODE simulation

---

myokit/_aux.py
myokit/_protocol.py
myokit/_sim/cvodesim.c
myokit/_sim/pacing.h
tests/ansic_event_based_pacing.py
tests/test_aux.py
tests/test_protocol.py
tests/test_protocol_floating_point.py
tests/test_simulation_cvode.py

Handle floating point issues in 'touching' protocol steps

---

myokit/lib/markov.py
tests/test_lib_markov.py

Add set_constant() method to markov simulations

---

myokit/lib/hh.py
myokit/lib/markov.py

and started pre-allocating arrays.
Fixes #270 . Fixes #332 .

Added log_times option to lib.markov.AnalyticalSimulation

---

myokit/lib/plots.py
tests/test_lib_plots.py

Added option to do something very similar to a current scape.
Fixes #335 (to some extent)

335 currentscape

---

myokit/lib/markov.py

Cache more matrices/solutions in markov sim

---

.appveyor.yml
.travis.yml
run-tests.py

Fix returncode set by unit tests

---

myokit/_myokit_version.py
myokit/formats/__init__.py
myokit/tests/test_formats.py

Add option to register external formats

---

myokit/_model_api.py
myokit/tests/test_model_api.py

Avoid certain prefixes when generating unames.

---

myokit/_datalog.py
myokit/tests/test_datalog.py

To find e.g. V(t = 123.456) for arbitrary t using linear interpolation

Add DataLog.interpolate_at(name, time) method.

---

myokit/_model_api.py
myokit/tests/test_model_api.py

Show unit in variable info (3d attempt)

---

myokit/formats/cellml/_exporter.py

Time variable in CellML export shouldn't have equation or initial value #369

---

myokit/formats/cellml/_exporter.py
myokit/tests/test_formats_cellml.py

CellML export: components now ordered alphabetically.

---

myokit/formats/cellml/_importer.py

Allow 'deca' prefix in CellML import

---

myokit/formats/cellml/_exporter.py
myokit/tests/test_formats_cellml.py

Export oxmeta annotations to CellML

---

.codecov.yml
.coveragerc
myokit/formats/cellml/_exporter.py

Add more ordering to CellML export.

---

myokit/_expressions.py

Add better 'is int' checking to units

---

myokit/lib/hh.py
myokit/tests/test_lib_hh.py

Allow HH model to have V-independent states

---

myokit/_model_api.py
myokit/tests/test_model.py

Add model.remove_derivative_references()

---

myokit/_model_api.py
myokit/tests/test_model.py

Fixed repr(Model) for models with no name.

---

myokit/lib/guess.py
myokit/tests/test_lib_guess.py

Variable meaning guessing module

---

myokit/lib/guess.py
myokit/tests/test_lib_guess.py

Guess stimulus current variables

---

myokit/__init__.py
myokit/__main__.py
myokit/formats/cellml/_importer.py
myokit/formats/cellml/cellml_1.py
myokit/tests/shared.py
myokit/tests/test_cellml_api.py
myokit/tests/test_formats_cellml.py

Made CellML importer use TextLogger

---

myokit/formats/cellml/cellml_1.py
myokit/formats/cellml/parser_1.py
myokit/tests/data/formats/cellml/documentation.cellml
myokit/tests/test_cellml_api.py
myokit/tests/test_cellml_parser.py
myokit/tests/test_expressions.py

And added method to replace non-ascii chars when flattening some docs.
Closes #428

CellML: Added checking for overdefinedness when importing

---

myokit/__init__.py
myokit/__main__.py
myokit/_aux.py
myokit/_sim/__init__.py
myokit/tests/shared.py

Shutil rmtree access issues on windows

---

myokit/__init__.py
myokit/__main__.py
myokit/formats/cellml/_exporter.py
myokit/formats/cellml/writer_1.py
myokit/gui/ide.py
myokit/lib/guess.py
myokit/tests/test_formats_cellml.py
myokit/tests/test_lib_guess.py
myokit/tests/test_system_info.py

CellML protocol export

---

myokit/formats/cellml/__init__.py
myokit/formats/cellml/_ewriter.py
myokit/formats/cellml/_exporter.py
myokit/formats/cellml/_importer.py
myokit/formats/cellml/v1/__init__.py
myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v1/_parser.py
myokit/formats/cellml/v1/_writer.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_cellml_v1_parser.py
myokit/tests/test_cellml_v1_writer.py

Reorganised CellML 1.0/1.1 api classes.

---

myokit/formats/cellml/__init__.py
myokit/formats/cellml/_exporter.py
myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v1/_writer.py
myokit/tests/test_cellml_v1_writer.py
myokit/tests/test_formats_cellml.py

Cellml version selection

---

myokit/_bin/example.mmt
myokit/formats/cellml/v1/_api.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_model.py

CellML export now infers units from RHS if no unit set.

---

myokit/formats/cellml/__init__.py
myokit/formats/cellml/_ewriter.py
myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v1/_parser.py
myokit/formats/cellml/v1/_writer.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_cellml_v1_parser.py
myokit/tests/test_cellml_v1_writer.py
myokit/tests/test_formats_cellml.py

Read and write oxmeta annotations

---

myokit/formats/cellml/v1/_api.py
myokit/tests/test_cellml_v1_api.py

CellML unit conversion

---

.travis.yml
run-tests.py

Documentation coverage checking

---

docs/source/api_formats/cellml.rst
docs/source/api_formats/cellml_v1.rst
docs/source/api_index/myokit.lib.rst
docs/source/api_library/guess.rst
myokit/__main__.py
myokit/_aux.py
myokit/formats/cellml/_importer.py
myokit/gui/ide.py
myokit/lib/guess.py
myokit/tests/test_aux.py
myokit/tests/test_lib_guess.py

Remove embedded stimulus protocol when importing model

---

.travis.yml
myokit/formats/cellml/v1/_api.py
run-tests.py

Free variable in CellML shouldn't have a value. 

---

myokit/_model_api.py
myokit/formats/cellml/_ewriter.py
myokit/formats/cellml/v1/_api.py
myokit/lib/guess.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_component.py
myokit/tests/test_formats_cellml.py
myokit/tests/test_lib_guess.py

Make adding/removing of embedded protocol in lib.guess reversible

---

myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v1/_parser.py
myokit/tests/test_cellml_v1_parser.py

Updated error messages for imports and initial values that are variables

---

.travis.yml
docs/source/api_index/myokit.lib.rst
docs/source/api_library/markov.rst
myokit/_expressions.py
myokit/_model_api.py
myokit/formats/sympy/_ereader.py
myokit/lib/hh.py
myokit/lib/markov.py
myokit/tests/test_formats_sympy.py
myokit/tests/test_lib_hh.py
myokit/tests/test_lib_markov.py
setup.py

Add methods to detect Markov states

---

myokit/lib/markov.py

LinearModel now converts to full ODE form.

---

docs/source/api_index/myokit.lib.rst
docs/source/api_library/guess.rst
myokit/lib/guess.py
myokit/tests/test_lib_guess.py

Add method to guess Cm

---

myokit/_aux.py
myokit/_expressions.py
myokit/_parsing.py
myokit/formats/cellml/v1/_api.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_expressions.py

Allow CellML export when myokit model has unit issues

---

myokit/formats/easyml/_exporter.py
myokit/tests/test_formats_easyml.py

Fixed EasyML issue for inf/tau variables used by more than one state.

---

myokit/_datalog.py
myokit/_model_api.py
myokit/_protocol.py
myokit/formats/easyml/_exporter.py
myokit/lib/common.py
myokit/lib/fit.py
myokit/lib/markov.py
myokit/lib/multi.py

Replaced logging.warning() with warnings.warn() where appropriate.

---

myokit/formats/cellml/v1/_parser.py
myokit/tests/test_cellml_v1_parser.py

Cellml fixes

---

docs/source/api_formats/cellml_v1.rst
docs/source/api_index/myokit.formats.rst
myokit/formats/cellml/v1/__init__.py
myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v1/_parser.py
myokit/formats/mathml/_parser.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_cellml_v1_parser.py
myokit/tests/test_formats_mathml_content.py
myokit/units.py

- Checking for in variable connected to multiple outs.

More CellML fixes

---

myokit/_aux.py

SubCapture issue on windows/spyder

---

myokit/_sim/__init__.py
myokit/_sim/fiber_tissue.py
myokit/_sim/opencl.py
myokit/_sim/openclsim.py

OpenCL on OS/X

---

.travis.yml
docs/source/api_formats/cellml_v2.rst
docs/source/api_index/myokit.formats.rst
myokit/formats/cellml/__init__.py
myokit/formats/cellml/_ewriter.py
myokit/formats/cellml/v2/__init__.py
myokit/formats/cellml/v2/_api.py
myokit/formats/cellml/v2/_parser.py
myokit/formats/cellml/v2/_writer.py
myokit/tests/data/formats/cellml/lr-1991-exported-2.cellml
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_cellml_v1_parser.py
myokit/tests/test_cellml_v1_writer.py
myokit/tests/test_cellml_v2_api.py
myokit/tests/test_cellml_v2_parser.py
myokit/tests/test_cellml_v2_writer.py
run-tests.py

See #49, #100, #470 
- model api
- parser
- writer
Needs to wait until CellML 2.0 is finalised, to double-check rules and especially rule numbers

CellML 2.0 tools.

---

myokit/_sim/__init__.py

Changed extra_linker_args to extra_link_args in CModule.

---

docs/source/api_formats/cellml.rst
docs/source/api_index/myokit.formats.rst
myokit/formats/cellml/__init__.py
myokit/formats/cellml/_exporter.py
myokit/formats/cellml/_importer.py
myokit/gui/ide.py
myokit/tests/data/formats/cellml/decker-2009.cellml
myokit/tests/test_formats_cellml.py
myokit/tests/test_formats_exporters.py

Added importer and exporter for CellML 2.0

---

.flake8
myokit/gui/ide.py

Fixed bug where GUI CellML export never added stimulus

---

myokit/_sim/cvodesim.c
myokit/tests/test_model.py
myokit/tests/test_protocol_floating_point.py
myokit/tests/test_simulation_cvode.py

535 cvode sim termination near event

---

.appveyor.yml

Reduced amount of appveyor testing

---

myokit/__init__.py
myokit/_aux.py
myokit/_model_api.py
myokit/_protocol.py
myokit/_sim/__init__.py
myokit/_sim/cvodesim.py

Pickling for model, protocol, simulation

---

myokit/formats/mathml/_parser.py
myokit/formats/sbml/_importer.py
myokit/formats/sbml/_parser.py
myokit/tests/data/formats/sbml/00004-sbml-l2v1-modified.xml
myokit/tests/data/formats/sbml/00004-sbml-l3v2-modified.xml
myokit/tests/test_formats_mathml_content.py
myokit/tests/test_formats_sbml.py
myokit/tests/test_mxml.py

Some further SBML updates

---

.codecov.yml

Removed codecov token

---

.travis.yml
myokit/_datalog.py
myokit/formats/sympy/__init__.py
myokit/formats/sympy/_ewriter.py
myokit/lib/multi.py
myokit/tests/test_formats_expression_writers.py
myokit/tests/test_formats_sympy.py
setup.py

Made sympy optional

---

myokit/__init__.py
myokit/_sim/__init__.py
myokit/_sim/cvodesim.py

Building with --inplace instead of --old-and-unmanageable

---

.appveyor.yml
myokit/_sim/__init__.py
myokit/_sim/cvodesim.py

Testing method to get myokit to work on windows and Python 3.8 again.

---

myokit/gui/__init__.py

Fixed matplotlib deprecation warning.

---

myokit/_expressions.py
myokit/_sim/cvodesim.c
myokit/gui/__init__.py
myokit/gui/ide.py
myokit/lib/deps.py

Possible, because expressions are immutable.
Slight speed-up if called repeatedly

Cache result of Expression.eval_unit()

---

myokit/lib/markov.py
myokit/tests/data/dom-markov.mmt
myokit/tests/test_lib_hh.py
myokit/tests/test_lib_markov.py

Fixed bug in Markov steady state code

---

myokit/_myokit_version.py
myokit/gui/ide.py

Reverts MichaelClerx/myokit#607

Revert "606 eval console"

---

myokit/gui/ide.py

IDE: Made eval error for Ctrl+E show in in console. 

---

myokit/_model_api.py
myokit/_sim/openclsim.cl
myokit/tests/data/lr-1991-dep.mmt
myokit/tests/test_dependency_checking.py

Component IO and RL

---

.appveyor.yml
.travis.yml
CONTRIBUTING.md
README.md

Changes to config and readme for master/develop --> main switch

---

CHANGELOG.md
CONTRIBUTING.md
LICENSE.txt
README.md
myokit/__init__.py

Added CHANGELOG.md

---

CHANGELOG.md
myokit/_datablock.py
myokit/_datalog.py
myokit/_sim/openclsim.py
myokit/tests/test_datablock.py

Add DataBlockNd.to_log methods

---

CHANGELOG.md
myokit/gui/datablock_viewer.py

DataBlockViewer now shows mouse coordinates for graph and video view.

---

CHANGELOG.md
myokit/gui/datablock_viewer.py

For blocks that don't start at t=0

Block viewer fix

---

CHANGELOG.md
myokit/_aux.py
myokit/tests/test_cellml_v2_writer.py
myokit/tests/test_formats_mathml_content.py
myokit/tests/test_lib_multi.py
myokit/tests/test_progress_reporters.py
myokit/tests/test_sbml_api.py

Various deprecation warnings

---

.travis.yml
CHANGELOG.md
myokit/_model_api.py
myokit/_sim/cvodesim.c
myokit/_sim/cvodesim.py
myokit/tests/test_simulation_cvode.py

See #671 
- CVODE returned slightly different error message in one test. Took this as a chance to make CVODE error output more uniform + informative.

Python 3.9 and CVODE 5 fixes

---

CHANGELOG.md
myokit/formats/cellml/v1/_api.py
myokit/formats/cellml/v2/_api.py
myokit/tests/test_cellml_v1_api.py
myokit/tests/test_cellml_v2_api.py

CellML inferred state variable units bug

---

CHANGELOG.md
myokit/_sim/__init__.py

Potential fix for windows DLL issue on 3.8.

---

myokit/_sim/mcl.h

Ran into it, was an extension so didn't add via macro in case it's undefined

Added another error to list of known OpenCL error codes.

---

CHANGELOG.md
myokit/_sim/fiber_tissue.py
myokit/_sim/opencl.py
myokit/_sim/openclsim.py

Closes #514 
Sorry for the shitty branch name, but it seems to work with your suggested changes.

#514 make requested changes

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/notebook-test.yml
.github/workflows/style-test.yml
.github/workflows/unit-tests-osx.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows-miniconda.yml
.github/workflows/unit-tests-windows.yml

Updated workflows to no longer build draft PRs.

---

myokit/_sim/cmodel.h
myokit/tests/test_simulation_cvode.py
myokit/tests/test_simulation_cvodes.py

Logging derivatives in cvodes sim

---

myokit/_sim/openclsim.c

Fixed long/int issue with setting connections in OpenCL that caused segfaults

---

myokit/_datablock.py

Fixed numpy deprecation warning.

---

CHANGELOG.md
myokit/_sim/mcl.h
myokit/_sim/opencl.c
myokit/_sim/opencl.py
myokit/_sim/openclsim.c
myokit/tests/shared.py
myokit/tests/test_simulation_opencl.py

Check for double support in opencl sim

---

CHANGELOG.md
myokit/_myokit_version.py
myokit/_sim/fiber_tissue.py

Deprecate fiber tissue sim

---

myokit/_sim/openclsim.cl

OpenCL tweak.

---

CHANGELOG.md
myokit/__main__.py
myokit/_datablock.py
myokit/_datalog.py
myokit/_sim/fiber_tissue.py
myokit/_sim/openclsim.c
myokit/_sim/openclsim.cl
myokit/_sim/openclsim.py
myokit/tests/test_datablock.py
myokit/tests/test_simulation_opencl.py

Opencl conductance fields.

---

myokit/_sim/openclsim.c
myokit/_sim/openclsim.py
myokit/tests/test_aux.py

Changed OpenCLsim error about double support to warning. 

---

CHANGELOG.md
myokit/gui/source.py

Made alt-up or down move lines in text editor.

---

CHANGELOG.md
myokit/__main__.py
myokit/_bin/install-lin/myokit-ide.desktop
myokit/_bin/install-lin/x-cellml.xml
myokit/gui/ide.py

IDE will now read cellml files from command line

IDE will now read cellml files from command line.

---

CHANGELOG.md
myokit/_model_api.py
myokit/tests/test_variable.py

And another convenience method to delete all child variables of a given variable

Added method to clamp variable to a value.

---

CHANGELOG.md
myokit/__main__.py
myokit/_aux.py
myokit/_model_api.py
myokit/_sim/cvodesim.py
myokit/_sim/cvodessim.py
myokit/_sim/fiber_tissue.py
myokit/_sim/openclsim.py
myokit/tests/test_cellml_v1_parser.py
myokit/tests/test_cellml_v2_parser.py
myokit/tests/test_lib_markov.py
myokit/tests/test_model.py
myokit/tests/test_parsing.py

Renamed Model.eval_state_derivatives Model.evaluate_derivatives.

---

CHANGELOG.md
myokit/gui/ide.py

Made IDE suggest filenames for model exports,

---

CHANGELOG.md
myokit/_datalog.py
myokit/tests/test_datalog.py

Made DataLog.save_csv() use a natural sort order.

---

myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py

Zero-step errors now raise an ArithmeticError so get nicer error output. 
See #756.

Updated exception types raised by CVODESSim internally.

---

CHANGELOG.md
docs/source/api_formats/sbml_api.rst
docs/source/api_index/myokit.formats.rst
myokit/formats/sbml/__init__.py
myokit/formats/sbml/_api.py
myokit/formats/sbml/_parser.py
myokit/tests/test_sbml_api.py
myokit/tests/test_sbml_parser.py

Added David's test showing issue #739.

---

CHANGELOG.md
myokit/_config.py
myokit/_sim/cvodesim.c
myokit/_sim/cvodessim.c
myokit/_sim/sundials.py
myokit/formats/ansic/_exporter.py
myokit/formats/ansic/template/sim.c

Autodetect cvode version

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/install-sundials-manually.sh
.github/workflows/style-test.yml
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-windows-miniconda.yml
.github/workflows/unit-tests-windows.yml

Test different sundials versions

---

.github/workflows/unit-tests-sundials.yml
CHANGELOG.md
myokit/_config.py
myokit/_sim/cvodesim.c
myokit/_sim/cvodessim.c
myokit/formats/ansic/template/sim.c
myokit/tests/test_simulation_cvode.py
myokit/tests/test_simulation_cvodes.py

See #819 
Object creation functions now require a "context" argument

Sundials 6.0.0 support

---

.coveragerc
CHANGELOG.md
myokit/__init__.py
myokit/__main__.py
myokit/_config.py
myokit/_sim/__init__.py
myokit/_sim/cable.c
myokit/_sim/cable.py
myokit/_sim/cvodesim.py
myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py
myokit/_sim/fiber_tissue.c
myokit/_sim/fiber_tissue.py
myokit/_sim/icsim.py
myokit/_sim/jacobian.py
myokit/_sim/mcl.h
myokit/_sim/opencl.c
myokit/_sim/openclsim.c
myokit/_sim/openclsim.py
myokit/_sim/psim.py
myokit/_sim/rhs.py
myokit/formats/opencl/template/cable.c
myokit/tests/ansic_event_based_pacing.py
myokit/tests/ansic_fixed_form_pacing.py
myokit/tests/test_config.py
myokit/tests/test_tools.py
myokit/tools.py

Add profiling to cvodes sim

---

CHANGELOG.md
myokit/__main__.py
myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py
myokit/tests/test_tools.py
myokit/tools.py

Use with `myokit.run script.mmt --debug-sp` or by setting `myokit.DEBUG_SP=True` before creating and running a sim

Added optional profiling info to CVODES sim.

---

myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py

CVODES sim checking of log_times argument now happens on the fly in C

---

CHANGELOG.md
myokit/formats/sbml/_api.py
myokit/tests/test_sbml_parser.py

#830 fix bug

---

CHANGELOG.md
myokit/gui/source.py

Updated highlighting and background colors in IDE

---

.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows.yml
CHANGELOG.md
myokit/__init__.py

No longer supported by github actions.

Dropped testing for 3.5

---

CHANGELOG.md
myokit/formats/cellml/_ewriter.py
myokit/formats/mathml/_ewriter.py
myokit/formats/mathml/_parser.py
myokit/tests/test_formats_cellml.py
myokit/tests/test_formats_mathml_content.py
myokit/tests/test_formats_mathml_presentation.py

E-notation in content mathml output

---

CHANGELOG.md
myokit/formats/cellml/v1/_writer.py
myokit/formats/cellml/v2/_writer.py
myokit/tests/test_cellml_v1_writer.py
myokit/tests/test_cellml_v2_writer.py

Tweaked the CellML export's initial_value attribute to strip e+00 if present.

---

CHANGELOG.md
myokit/gui/ide.py
myokit/gui/source.py

Better syntax highlighting

---

myokit/gui/source.py

Set selected line colour explicitly in IDE (not via system palette).

---

.github/workflows/unit-tests-windows.yml
CHANGELOG.md

No longer supported: https://github.com/MichaelClerx/myokit/actions/runs/1910495527

No longer testing on 3.6 on windows.

---

CHANGELOG.md
myokit/_sim/pacing.h

Decreffed a list in pacing populate.

---

.github/workflows/install-sundials-manually.sh
CHANGELOG.md
myokit/_datalog.py
myokit/_system.py
myokit/gui/datalog_viewer.py

More stuff in 'myokit system'

---

.gitignore
CHANGELOG.md
myokit/_sim/cvodessim.c

859 memory leak cvodessim

---

myokit/_sim/cvodesim.py
myokit/tests/memory/README.md
myokit/tests/memory/decref.py
myokit/tests/memory/memleak.py

Offline tests for memory leaks

---

.github/workflows/install-ubuntu-dependencies.sh
myokit/tests/test_aux.py
myokit/tests/test_model.py

Using newer opencl runtime in tests

---

myokit/_unit.py

Clarify docs for Unit.conversion_factor with "helpers"

---

setup.py

Tiny change to trigger test re-run

---

CHANGELOG.md
myokit/_unit.py

Unit.conversion_factor doc tweak.

---

CHANGELOG.md
myokit/_model_api.py

Allowing you to e.g. print an update on what's happening

Variable.convert_unit now returns True if conversion took place.

---

CHANGELOG.md
myokit/_model_api.py

Small improvements to model, component, and variable documentation.

---

CHANGELOG.md
myokit/__init__.py
myokit/__main__.py
myokit/_config.py
myokit/_sim/__init__.py
myokit/tests/test_config.py

Add no_capture option to ini

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/style-test.yml
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows-miniconda.yml
.github/workflows/unit-tests-windows.yml
myokit/tests/test_expressions.py

- New versions
- Unrelated fix to test_expressions

Updates to github action workflows & fixed expression test

---

CHANGELOG.md
myokit/_sim/__init__.py
myokit/_sim/mcl.h
myokit/_sim/openclsim.c
myokit/_sim/pacing.h

See #902 
Fixes to separate issues:
- lots of implicit conversion between various int types
- makes `clSetKernelArg` use the arg size `sizeof(cl_mem)` for any buffer arguments

OpenCL data type issues

---

myokit/_config.py

Added homebrew location to myokit.ini on mac.

---

.github/workflows/coverage-test.yml
CHANGELOG.md
myokit/tests/test_expressions.py

Consistent coverage of `_proper` check in `Expression.depends_on`

---

.github/workflows/install-ubuntu-dependencies.sh

See #881
Suddenly became urgent as old ubuntu opencl unit tests no longer seem to work

Can we install opencl on ubuntu purely with apt-get?

---

.flake8
.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/select-opencl-device.py
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows-miniconda.yml
.github/workflows/unit-tests-windows.yml
myokit/_sim/opencl.py

Select the device with double support, if available

Looking into cl device selection for unit tests

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/style-test.yml
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows.yml

Testing with pip cache

---

CHANGELOG.md
myokit/gui/source.py
myokit/lib/deps.py

Made syntax highlighting in IDE recognise units containing - and *.

---

CHANGELOG.md
docs/source/api_gui/datalog_viewer.rst
docs/source/api_index/myokit.gui.rst
myokit/gui/datalog_viewer.py

- Overlay traces called e.g. 0.membrane.V and 1.membrane.V
- Switch between open files with Ctrl + Page up or down
- Switch between graphs with Page up and down

DataLog viewer tweaks

---

CHANGELOG.md
myokit/__init__.py
myokit/_aux.py
myokit/_model_api.py
myokit/_sim/cable.c
myokit/_sim/cmodel.py
myokit/_sim/fiber_tissue.py
myokit/_sim/openclsim.py
myokit/_sim/rhs.c
myokit/formats/ansic/template/cable.c
myokit/formats/ansic/template/euler.c
myokit/formats/ansic/template/sim.c
myokit/formats/cuda/template/kernel.cu
myokit/formats/matlab/_exporter.py
myokit/formats/opencl/_exporter.py
myokit/formats/python/template/sim.py
myokit/formats/stan/_exporter.py

Moved prepare bindings

---

CHANGELOG.md
myokit/_datalog.py
myokit/gui/datalog_viewer.py
myokit/tests/test_datalog.py
setup.py

Move scipy from required dependencies to optional extras

---

myokit/tests/test_simulation_cvodes.py

Including one that mixes time series and event-based

Added more tests for multi-protocol runs.

---

CHANGELOG.md
myokit/_bin/install-win/menu.json
myokit/gui/ide.py

- #508 Not sure where to start, but these changes to menu.json _might_ solve it.
- #648 Clarified console message after re-build
- #656 IDE options "Validate" and "Jump to last error" now do model on model tab, protocol on protocol tab, or nothing on script tab

Various small IDE fixes

---

CHANGELOG.md
myokit/__init__.py
myokit/__main__.py
myokit/_config.py

Just use warnings instead
#987

Stop using the `logging` module

---

CHANGELOG.md
docs/source/syntax/model.rst
docs/source/syntax/protocol.rst
myokit/_sim/cable.py
myokit/_sim/cmodel.h
myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py
myokit/_sim/fiber_tissue.py
myokit/_sim/openclsim.py
myokit/_sim/pacing.h
myokit/tests/ansic_time_series_pacing.c
myokit/tests/ansic_time_series_pacing.py
myokit/tests/test_pacing_system_c.py
myokit/tests/test_simulation_1d.py
myokit/tests/test_simulation_cvodes.py
myokit/tests/test_simulation_fiber_tissue.py
myokit/tests/test_simulation_opencl.py

Value of `pace` when no protocol is set

---

CHANGELOG.md
myokit/_protocol.py
myokit/_sim/cable.c
myokit/_sim/cvodessim.c
myokit/_sim/fiber_tissue.c
myokit/_sim/openclsim.c
myokit/_sim/openclsim.py
myokit/_sim/pacing.h
myokit/tests/ansic_event_based_pacing.c
myokit/tests/ansic_event_based_pacing.py
myokit/tests/test_pacing_system_c.py
myokit/tests/test_pacing_system_py.py
myokit/tests/test_simulation_1d.py
myokit/tests/test_simulation_cvodes.py
myokit/tests/test_simulation_fiber_tissue.py
myokit/tests/test_simulation_opencl.py

Negative times are now allowed. 

---

.coveragerc
CHANGELOG.md
docs/source/api_formats/axon.rst
docs/source/api_formats/heka.rst
docs/source/api_formats/wcp.rst
docs/source/api_index/myokit.formats.rst
myokit/formats/__init__.py
myokit/formats/axon/_abf.py
myokit/formats/heka/__init__.py
myokit/formats/heka/_importer.py
myokit/formats/heka/_patchmaster.py
myokit/formats/wcp/_wcp.py

HEKA Patchmaster data format

---

docs/source/api_formats/heka.rst
docs/source/api_gui/datalog_viewer.rst
docs/source/api_index/myokit.gui.rst
myokit/formats/heka/_patchmaster.py
myokit/gui/datalog_viewer.py

Closes #1000 
Also added heka viewing to datalog viewer

Make heka loading deal with storage of segments

---

myokit/formats/heka/_patchmaster.py

Several properties from Trace and AmplifierState, plus updated meta_str()

More meta data in PatchMasterFile.

---

CHANGELOG.md
myokit/_model_api.py
myokit/tests/test_model.py
myokit/tests/test_model_building.py

- Added keyword arguments to add_variable for one-line creation. Closes #1011 
- ~Checking that variables aren't bound and labelled at the same time.~

Added keyword arguments to add_variable for one-line creation. 

---

CHANGELOG.md
myokit/gui/__init__.py
myokit/gui/explorer.py
myokit/gui/source.py
myokit/tests/test_datalog.py

Stopped making explorer fields white in dark mode.

---

CHANGELOG.md
myokit/lib/plots.py

Always raised deprecation warning 🙈

Fixed bug in deprecation warning for normalise arg in cumulative_current.

---

CODE_OF_CONDUCT.md
README.md

See https://www.contributor-covenant.org/

Adding contributor code of conduct

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/style-test.yml
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows-miniconda.yml
.github/workflows/unit-tests-windows.yml
myokit/formats/heka/_patchmaster.py

Plus updates to the github actions

Heka tweaks

---

myokit/__init__.py
myokit/__main__.py
myokit/_sim/cvodessim.c
myokit/_sim/cvodessim.py

`myokit run example --debug-ss`
```
1. number of steps taken by cvodes.
2. number of calls to the user's f function.
3. number of calls made to the linear solver setup function.
4. number of error test failures.
5. method order used on the last internal step.
6. method order to be used on the next internal step.
7. actual value of initial step size.
8. step size taken on the last internal step.
9. step size to be attempted on the next internal step.
10. current internal time reached.
1	2	3	4	5	6		7		8		9		10
1,	4,	1,	0,	1,	1,	0.105536,	0.105536,	0.376822,	0.105536
2,	5,	2,	0,	1,	1,	0.105536,	0.376822,	2.38867,	0.482358
3,	7,	3,	0,	1,	1,	0.105536,	2.38867,	2.38867,	2.87103
4,	8,	3,	0,	1,	2,	0.105536,	2.38867,	13.0418,	5.2597
5,	12,	5,	1,	2,	2,	0.105536,	6.70673,	6.70673,	11.9664
6,	13,	5, …
```

Added cvode stats printing debug mode

---

.github/workflows/unit-tests-sundials.yml
CHANGELOG.md
myokit/_sim/cvodessim.c

Adding support for Sundials 7

---

.github/workflows/unit-tests-macos.yml
CHANGELOG.md
myokit/_sim/mcl.h

Bumping minimum supported Python to 3.8

---

.github/workflows/unit-tests-numpy.yml
CHANGELOG.md
myokit/_datablock.py
myokit/_datalog.py
myokit/_sim/jacobian.py
myokit/_sim/openclsim.py
myokit/_sim/rhs.py
myokit/formats/opencl/template/minilog.py
myokit/lib/markov.py
myokit/lib/plots.py
myokit/tests/test_datablock.py
myokit/tests/test_model.py

Mostly replacing `np.array(x, copy=False)` with `np.asarray(x)`

Updates for Numpy 2 compatibility

---

.github/workflows/coverage-test.yml
.github/workflows/docs-test.yml
.github/workflows/style-test.yml
.github/workflows/unit-tests-macos.yml
.github/workflows/unit-tests-numpy.yml
.github/workflows/unit-tests-sundials.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows.yml
CHANGELOG.md

Testing on Python 3.12 and 3.13

---

myokit/_datalog.py

Updated docs of fold and split_periodic to refer to each other.

---

.github/workflows/docs-test.yml
.github/workflows/unit-tests-ubuntu.yml
.github/workflows/unit-tests-windows.yml

Not supported on actions anymore

No longer testing on 3.7

---

CHANGELOG.md
myokit/gui/datalog_viewer.py

Add close and close all menu options to data log viewer

---

CHANGELOG.md
myokit/formats/heka/_patchmaster.py

Now all in kHz and can be obtained numerically

Patchmaster filter frequencies methods

---

CHANGELOG.md
myokit/formats/heka/_patchmaster.py

And added detailed Cfast meta data

Documented patchmaster file doesn't have prediction info.
